### Pandas

* Скачайте любой табличный датасет (можете использовать тот же, что и в дз к занятию "Знакомство с библиотеками"), например, с https://www.kaggle.com/datasets
* Проведите поноценный EDA 
    * "погрузитесь" в данные
    * составьте описание измерений из датасета
    * очистите данные, если это необходимо
    * попробуйте создать дополнительные переменные, которые могут помочь лучше понять данные

### Numpy

1. Вычислите A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

2. Найдите матрицу С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

3. Вычислите С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

4. Вычислите определитель матрицы А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

5. Вычислите матрицу, обратную матрице А. И покажите, что она действительно является обратной
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [1]:
import numpy as np

a = np.array([[1, -2, 4], [2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6, 2]])
a, b

(array([[ 1, -2,  4],
        [ 2,  0, -1]]),
 array([[5, 2, 3],
        [4, 6, 2]]))

In [2]:
print(a + b)
print(a - b)

[[6 0 7]
 [6 6 1]]
[[-4 -4  1]
 [-2 -6 -3]]


In [3]:
a = np.array([[1, 2], [2, -1], [3, 0]])
b = np.array([[-1 ,1], [1, 2], [0, 0]])
a, b

(array([[ 1,  2],
        [ 2, -1],
        [ 3,  0]]),
 array([[-1,  1],
        [ 1,  2],
        [ 0,  0]]))

In [5]:
c = a - 3*b
c

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

In [6]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])
a, b

(array([[ 1, -1],
        [ 2,  0],
        [ 3,  0]]),
 array([[1, 1],
        [2, 0]]))

In [7]:
c = a@b
c

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

In [8]:
a = np.array([[6, -1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

In [11]:
d = np.array([[3, 3, -1], [4, 1, 3], [1, -2, 2]], dtype='int64')
e = np.linalg.inv(d)
d, e, d@e

(array([[ 3,  3, -1],
        [ 4,  1,  3],
        [ 1, -2,  2]]),
 array([[ 0.44444444, -0.22222222,  0.55555556],
        [-0.27777778,  0.38888889, -0.72222222],
        [-0.5       ,  0.5       , -0.5       ]]),
 array([[ 1.00000000e+00, -1.11022302e-16,  1.11022302e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  1.11022302e-16,  1.00000000e+00]]))